# Equity Convex Rate Hedge Strategy Configuration
name: equity_convex_rate
description: "TQQQ + PFIX rate hedge + gold + cash with regime-switching"

# Assets
assets:
  core: "TQQQ"
  rate_hedge: "PFIX" # Payer-swaption rate hedge
  diversifier: "IAU" # Gold
  cash: "SGOV"

# Strategy Parameters
regime_switching:
  correlation_threshold: 0.0
  positive_correlation_allocation:
    pfix_weight: 0.2
    gold_weight: 0.15
  negative_correlation_allocation:
    tmf_weight: 0.15 # Allow some TMF when correlation < 0
    gold_weight: 0.1

tqqq_overweight:
  base_weight: 0.6
  expected_return_tilt: 0.05

volatility_targeting:
  target_vol: 0.15
  lookback_period: 60

rebalancing:
  frequency: "monthly"
  drift_bands: 10
